<script type="text/javascript" src="<?=base_url()?>application/third_party/AnyChart/anychart-bundle.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>theme/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>theme/assets/global/plugins/jquery-nestable/jquery.nestable.js"></script>
<script type="text/javascript" src="<?=base_url()?>application/third_party/DSG/numeral.js"></script>
<script type="text/javascript" src="<?=base_url()?>application/third_party/jquery-typeahead-2.6.1/src/jquery.typeahead.js"></script>
<script type="text/javascript" src="<?=base_url()?>application/third_party/handlebars/handlebars-4.05.js"></script>
<script type="text/javascript" src="<?=base_url()?>theme/assets/global/plugins/bootbox/bootbox.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>application/third_party/MarkDown/simplemde.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>application/third_party/MarkDown/marked.js"></script>
<script type="text/javascript" src="<?=base_url()?>application/third_party/DataTables/datatables.min.js"></script>
<script type="text/javascript" src="<?=base_url()?>theme/assets/global/plugins/bootstrap-toastr/toastr.min.js"></script>
